import type { Category, Product, Banner } from '../types';

export const mockCategories: Category[] = [
  { id: '1', name: 'Obra Gruesa', slug: 'obra-gruesa', icon: 'construction' },
  { id: '2', name: 'Terminaciones', slug: 'terminaciones', icon: 'paintbrush' },
  { id: '3', name: 'Herramientas', slug: 'herramientas', icon: 'wrench' },
  { id: '4', name: 'Plomería', slug: 'plomeria', icon: 'droplet' },
  { id: '5', name: 'Electricidad', slug: 'electricidad', icon: 'zap' },
  { id: '6', name: 'Pinturas', slug: 'pinturas', icon: 'palette' },
  { id: '7', name: 'Pisos', slug: 'pisos', icon: 'grid' },
  { id: '8', name: 'Cocinas', slug: 'cocinas', icon: 'home' },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Cemento Portland Compuesto CP40',
    slug: 'cemento-portland-compuesto-cp40',
    description: 'Cemento Portland compuesto de alta resistencia, ideal para hormigón armado, estructuras y fundaciones. Cumple norma IRAM 50000.',
    price: 12500,
    stock_status: true,
    category_id: '1',
    image_url: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=400&h=400&fit=crop',
    brand: 'Loma Negra',
    sku: 'LN-CPC-40',
    unit: '50 Kg',
    badge: 'OFERTA SEMANA',
    specifications: { Peso: '50Kg', Rendimiento: '1m² (aprox. según mezcla)', Origen: 'Argentina', Material: 'Portland Compuesto', Norma: 'IRAM 50000' },
    images: [
      'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=600&fit=crop',
    ],
    category: { id: '1', name: 'Obra Gruesa', slug: 'obra-gruesa' },
  },
  {
    id: '2',
    name: 'Hierro Aletado de Construcción 10mm',
    slug: 'hierro-aletado-construccion-10mm',
    description: 'Barra de hierro aletado para armadura de hormigón. Acero ADN 420, laminado en caliente.',
    price: 45000,
    stock_status: true,
    category_id: '1',
    image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&h=400&fit=crop',
    brand: 'Acindar',
    sku: 'AC-HA-10',
    unit: 'Barra 12m',
    badge: 'POPULAR',
    specifications: { Diámetro: '10mm', Largo: '12m', Material: 'Acero ADN 420', Norma: 'IRAM-IAS U 500-528' },
    images: [
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=600&fit=crop',
    ],
    category: { id: '1', name: 'Obra Gruesa', slug: 'obra-gruesa' },
  },
  {
    id: '3',
    name: 'Ladrillo Hueco 12×18×33 9 Tubos',
    slug: 'ladrillo-hueco-12x18x33',
    description: 'Ladrillo cerámico hueco de 9 tubos, ideal para tabiques y cerramientos.',
    price: 320,
    stock_status: true,
    category_id: '1',
    image_url: 'https://images.unsplash.com/photo-1590079110492-1039e8db0883?w=400&h=400&fit=crop',
    brand: 'Palmar',
    sku: 'PM-LH-1218',
    unit: 'Unidad',
    specifications: { Medidas: '12×18×33 cm', Tubos: '9', Material: 'Cerámica', Uso: 'Tabiques y cerramientos' },
    images: [
      'https://images.unsplash.com/photo-1590079110492-1039e8db0883?w=600&h=600&fit=crop',
    ],
    category: { id: '1', name: 'Obra Gruesa', slug: 'obra-gruesa' },
  },
  {
    id: '4',
    name: 'Látex Interior Albalatex Mate 20L',
    slug: 'latex-interior-albalatex-mate-20l',
    description: 'Pintura látex para interiores, acabado mate, excelente poder cubritivo y lavabilidad.',
    price: 18500,
    stock_status: true,
    category_id: '6',
    image_url: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400&h=400&fit=crop',
    brand: 'Alba',
    sku: 'AL-LAM-20',
    unit: 'Balde 20L',
    specifications: { Contenido: '20 Litros', Rendimiento: '10-12 m²/L', Acabado: 'Mate', Dilución: '20-30% agua' },
    images: [
      'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600&h=600&fit=crop',
    ],
    category: { id: '6', name: 'Pinturas', slug: 'pinturas' },
  },
  {
    id: '5',
    name: 'Amoladora Angular Professional 750w',
    slug: 'amoladora-angular-professional-750w',
    description: 'Amoladora angular profesional de 750W, disco de 115mm, ideal para corte y desbaste.',
    price: 42000,
    stock_status: true,
    category_id: '3',
    image_url: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&h=400&fit=crop',
    brand: 'Bosch',
    sku: 'BO-AG-750',
    unit: 'Unidad',
    badge: 'ENVÍO GRATIS',
    specifications: { Potencia: '750W', Disco: '115mm (4½")', Velocidad: '11.000 RPM', Peso: '1.8 Kg' },
    images: [
      'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600&h=600&fit=crop',
    ],
    category: { id: '3', name: 'Herramientas', slug: 'herramientas' },
  },
  {
    id: '6',
    name: 'Porcelanato Rectificado Gris 60x120',
    slug: 'porcelanato-rectificado-gris-60x120',
    description: 'Porcelanato rectificado gris pulido, ideal para pisos y revestimientos de alto tránsito.',
    price: 8500,
    stock_status: true,
    category_id: '7',
    image_url: 'https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=400&h=400&fit=crop',
    brand: 'Lourdes',
    sku: 'LO-PRG-6012',
    unit: 'm²',
    badge: 'HOT SALE',
    specifications: { Medidas: '60×120 cm', Acabado: 'Pulido rectificado', PEI: '4', Espesor: '10mm' },
    images: [
      'https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=600&h=600&fit=crop',
    ],
    category: { id: '7', name: 'Pisos', slug: 'pisos' },
  },
  {
    id: '7',
    name: 'Mezcla Adhesiva Impermeable',
    slug: 'mezcla-adhesiva-impermeable',
    description: 'Adhesivo cementicio impermeable para colocación de cerámicos y porcelanatos en zonas húmedas.',
    price: 9800,
    stock_status: true,
    category_id: '2',
    image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&h=400&fit=crop&q=80',
    brand: 'Klaukol',
    sku: 'KL-MAI-30',
    unit: 'Bolsa 30kg',
    specifications: { Peso: '30Kg', Rendimiento: '4-6 Kg/m²', 'Tiempo abierto': '20 min', Uso: 'Interior/Exterior' },
    images: [
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=600&fit=crop&q=80',
    ],
    category: { id: '2', name: 'Terminaciones', slug: 'terminaciones' },
  },
  {
    id: '8',
    name: 'Chapa Acanalada Galvanizada C25',
    slug: 'chapa-acanalada-galvanizada-c25',
    description: 'Chapa de acero galvanizada acanalada, calibre 25, para techos y cerramientos.',
    price: 15200,
    stock_status: true,
    category_id: '1',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=400&fit=crop',
    brand: 'Ternium',
    sku: 'TN-CAG-C25',
    unit: 'Metro Lineal',
    specifications: { Calibre: 'C25', Material: 'Acero Galvanizado', Ancho: '1.10m', Espesor: '0.50mm' },
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop',
    ],
    category: { id: '1', name: 'Obra Gruesa', slug: 'obra-gruesa' },
  },
  {
    id: '9',
    name: 'Piedra Partida 6-20 Granítica',
    slug: 'piedra-partida-6-20-granitica',
    description: 'Piedra partida granítica 6-20mm para hormigón estructural y contrapisos.',
    price: 28000,
    stock_status: true,
    category_id: '1',
    image_url: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=400&h=400&fit=crop',
    brand: 'Cantera Local',
    sku: 'CL-PPG-620',
    unit: 'Metro Cúbico',
    specifications: { Granulometría: '6-20mm', Material: 'Granito', Densidad: '1.450 Kg/m³', Uso: 'Hormigón estructural' },
    images: [
      'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=600&h=600&fit=crop',
    ],
    category: { id: '1', name: 'Obra Gruesa', slug: 'obra-gruesa' },
  },
  {
    id: '10',
    name: 'Cal Hidratada 25kg',
    slug: 'cal-hidratada-25kg',
    description: 'Cal hidratada de primera calidad para revoques, mamposterías y pinturas a la cal.',
    price: 3200,
    stock_status: true,
    category_id: '1',
    image_url: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=400&h=400&fit=crop&q=80',
    brand: 'Holcim',
    sku: 'HO-CH-25',
    unit: 'Bolsa 25Kg',
    specifications: { Peso: '25Kg', Material: 'Cal Hidratada', Norma: 'IRAM 1508', Uso: 'Revoques y mamposterías' },
    images: [
      'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=600&h=600&fit=crop&q=80',
    ],
    category: { id: '1', name: 'Obra Gruesa', slug: 'obra-gruesa' },
  },
  {
    id: '11',
    name: 'Taladro Percutor Inalámbrico 18V',
    slug: 'taladro-percutor-inalambrico-18v',
    description: 'Taladro percutor inalámbrico de 18V con batería de litio, mandril de 13mm.',
    price: 65000,
    stock_status: true,
    category_id: '3',
    image_url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&h=400&fit=crop',
    brand: 'Bosch',
    sku: 'BO-TPI-18',
    unit: 'Unidad',
    specifications: { Voltaje: '18V', Mandril: '13mm', Torque: '50Nm', Batería: 'Li-Ion 2.0Ah' },
    images: [
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&h=600&fit=crop',
    ],
    category: { id: '3', name: 'Herramientas', slug: 'herramientas' },
  },
  {
    id: '12',
    name: 'Caño de Agua Termofusión 25mm',
    slug: 'cano-agua-termofusion-25mm',
    description: 'Caño de polipropileno para agua fría y caliente, unión por termofusión.',
    price: 2800,
    stock_status: true,
    category_id: '4',
    image_url: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400&h=400&fit=crop',
    brand: 'Acqua System',
    sku: 'AS-CT-25',
    unit: 'Barra 4m',
    specifications: { Diámetro: '25mm', Largo: '4m', Material: 'Polipropileno', 'Temp. máx': '95°C' },
    images: [
      'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&h=600&fit=crop',
    ],
    category: { id: '4', name: 'Plomería', slug: 'plomeria' },
  },
];

export const mockBanners: Banner[] = [
  {
    id: '1',
    image_url: '',
    title: 'OFERTAS DE OBRA',
    subtitle: 'Equipá tu proyecto con los mejores precios del mercado. Solo por tiempo limitado.',
    cta_text: 'VER CATÁLOGO COMPLETO',
    cta_link: '/productos',
  },
  {
    id: '2',
    image_url: '',
    title: 'HOT SALE HERRAMIENTAS',
    subtitle: 'Hasta 30% OFF en herramientas profesionales Bosch, Stanley y DeWalt.',
    cta_text: 'VER OFERTAS',
    cta_link: '/productos?categoria=herramientas',
  },
  {
    id: '3',
    image_url: '',
    title: 'ENVÍO GRATIS',
    subtitle: 'En compras mayores a $50.000 dentro de CABA y GBA. Entregas programadas.',
    cta_text: 'COMPRAR AHORA',
    cta_link: '/productos',
  },
];
